"""add project ai analysis

Revision ID: 8034db4af01b
Revises: 6b2f0d4a8c91
Create Date: 2026-08-16 13:01:08.476528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8034db4af01b'
down_revision: Union[str, Sequence[str], None] = '6b2f0d4a8c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_ai_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('result_factors_json', sa.Text(), nullable=True),
    sa.Column('result_strengths_json', sa.Text(), nullable=True),
    sa.Column('result_weaknesses_json', sa.Text(), nullable=True),
    sa.Column('result_competitor', sa.Text(), nullable=True),
    sa.Column('result_caveat', sa.Text(), nullable=True),
    sa.Column('result_preliminary', sa.Boolean(), nullable=False),
    sa.Column('decision_risks_json', sa.Text(), nullable=True),
    sa.Column('decision_risks_preliminary', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_ai_analyses_project_id'), 'project_ai_analyses', ['project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_ai_analyses_project_id'), table_name='project_ai_analyses')
    op.drop_table('project_ai_analyses')
    # ### end Alembic commands ###
